let zhejiang = {
    "type": "FeatureCollection",
    "features": [
        {
            "id": "330100",
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    "@@XBFBF@DGFWFK@CDO@MCE@CFKBID@HFLBAKECAKBMFCBOCCBKSMDE@MOKEG@EMGIACACCBCDCNBFI@Q@ALA^IHCBGDBJHDBTBbLjHBE@MIGOAOYDAGULI@CVKPMHANMLR@JhHFPHTDNÎAÈBRA¨UFAHGFMBk@[BkJWHGPMyqq{u_AEcuWkEYCCKAQGCAIBEH_@IEC@A@CHMHkDICGAUFGDGLGHaHGGGDOAEOBOEACCAAM@CICCAQA@aEIBAFBJDFCDAABBABA@BB@D@A@DA@AE@@ADABD@@BCBACACEA@BG@BaEECACBBNABM@ABBF@DIFEFCNCDEAAAU@OECAEGIHC@@GDIAA[@@GIGEIGIKFCCCBCPADEBQGGGCABCL@@AGMIEEIIE@GDGJCJAJFJLHBZQLADCDGBEAMCMHEBC@SGECGMGAENQHAJBFAFYAE@ALCLM@MLMCK@EDEAEFGCGGCYBGQ@ICIMGCCKG@MGCOS]JCBEBEDCCCMGICAGAGAQJ@NGPCDGFCAEKEAE@GFYBKFOEKKOE@CHI@AMKOUECC@IFGB@HEFIDC@KQAGEAIDAAAI@ICCDG@EAIGMQQIMQKGAQKQ]@GDGMMEAEDIFILEDEAUK]DWCCIIMAGJKDWMK@WACE@C@CCCCIAEAAC@GOCWCGDABKDABANG@MEAEIIC@YBEAOIGAKICBAFADMDCFABKCE@QNGDC@@ICGBADETKCGBGDOHALKBCAG@EHKACFGJGLBHCDDGFADBBFDJBDADAFAFCHGL@FCNCLIBWAICEYDSGOACAE@UFEAAISFEGYCUDCBGHGDCAGDIAIDE@IESNKDABBFABUUE@GDCAIIACIAKIAECAE@CAESOMGWAKHO@QKIMCCA@CBCBECC@CFEBEEQIG@AHE@EAEIAECKGE@MDAASEIEEEDGPKDGTODEACCCMEQ@@C@AOEAEBWACKIKWDEAIBEBEHCDOCGEEAEBEACCAM@EBGJC@A@AK@QAEKEGAEDELE@KAIFGAMDCJEBCAQSOG@QOUKIIAAAAGBAXOBCBOECE@IDGAMFIJGBMBGAGKQAOBAAKGK@IDCDEDAAICKIDCBGCICISWEIODC@OGYBCF@LCHIHCBIAEDCLIRFJGPCNDH@DEPOLCHBHEF@PCBQC@EHGKSOCEAE@C@EEC@AB@JEHGDI@IfKDGCOYCCMBC@GKSCC@KFA@KWGE@CBCJCDCBEFCBCAEBCGIAKBEGSDIDAH@JKFK@EGSFABCBACEMCaMAA@CLK@I@CE@CFAB@KBCAGIIIA]@KFGAEA@CFQACGAAAAGEAECCIECWG]HKAA@DRGHCPCDGFABDL@BGDKEUDEHIDCKDG@EBAAAHA@AACE@ECKM@E@CDADAFDDAHITKCAAA@QAIFKCCCAE@CBCLMACBEAAA@EHGBC@CIUYDAHKLCDODMLCBKII@EEMBABAJFRKBE@cSWBCFM@ECACGEC@MDK@OGS@OIMCcESICBEPGDEHIHAH@JAJFHILGTCAABKLEHGAA@OTCBEFADFFTHDD@FABYFCDGJAB_FGJMFGJMJCFEDOGCICAE@OHQGQOGKAKCCIEMAGGEEME@ECGIAIDIAeYMACOEAACAACEEAM@C@CECOJMAIBM[QS@GCKGACCIOCOQMAMFYRGDQCK@eG[IG@K@CHDFHFBHC\\EBGAI@ENEFAFKNPPBHGNCJEJ@BFJ@HBFD@NEDBDKNMJEB@BBAHIVMNKPGHFNGHUTBNEHIFOEAJABC@IAIHEDS@UECBMBAHCDUDK@GA@DJRBJADEBGBEAQGGFQBCFGDOAQMMBSNIPEBEAEBSLMJAFHLAFMFEDOBCD@B@BJJDFBHIFIDQCIBGFCLKBGDO\\EBWDADAHIP@TDCNBJDHNNNHLLLDFDJB@REX@TDLAJGJANDFJBCDBLHTMFARDRHVLLB@FAVDJBPEPHR@NDPJD^PXHHBJRDJPTFADBJNNLBNFHFBlLN@dT\\IHGHEH@HFJHFLTRLHDD@JBBLJBBBNRLBJPPdFLNBLDHNHHJDDJDBDBLDHBP@FGLDJEPKJCHB`DRFFFDXAD@NNKJQD@DFN@LXHPGJEJBHFDLRNHDLNRLDBJHNHVRHP@bCJAPCDCLBDDDNBTELAHFBHHFLCLKTAB@ETBTCDBHDPHLDJEJIL@DFH@JAFGHDFLHJXAFKBKRDFJJ@FEFKNEDMBCLAPCFAL@NGN@D@HFLDDNDJ@FD@H@JJLDFDP@HCBGCS@MBGFIBGEKAGDIHCDDJBDJHXFxVVFDHL@DDFLJHPFBB@HGNKDO@MBCDEJGXEJ@FEDKDED@FBBPDGLAPM^APFHBH@LCP@FTDVLTRPBJDLLNFDLAD\\PJBBABMFIJFFBF@FGB@ZDB@BEAKBOfIJKLAHIFCHARATBDCDILCF@FBHFNPRLPDFADCFCHAFELGRALIF@nAHADGDAD@FBD@JGHAJBRG\\@DPDDJCF@JDB@FCBABMBEHBJHHPPjCFEBADFNJNJAJEH@HBLHJAD@XRPPFLvPD@PILGDCBMHIN@hLLFJLLFH@HBFLH@XFFFHFJDFDDJJ@LPJZJ@XGT@NBN@PC^IHBJDNHJBDDBFCLBHRNDHJJ^HFEFGBKNMDATCJBRJLANBTLPPDBJCFCBOWCCAACJe@ECCCA@APCHCLAPDH@LD\\TJRVRVHBBBFCFEFCJOP@N@JJBDFBJLX@FGNHD@DBVEN@JCJGJKXC\\@DBBPADBHDHLLCHGPQ^CJ@HBb@DCBEEQA]ACICAAJGdEVMHBdJF@VMFIHCJ@JDBHDBBAB@FQLOJEDIFAJBF@FC@CKECG@IBCVANEHAF@FFDBJED@RJFBH@HEDEBOFCHAJBJAHG@EFITEHBBBJLPLHBbCD@FIHEXAN@VCFABCBEH@NDNBBBEHHDDH@HEJEDELBPAPBFJLF^PAFBDBfCBCGIBGDCPCFGBAH@PFjHHABEAMFIVFDFFBL@HFCF@HB@JEBDEFBFIHHBDCNFGD@@BBADFFXDAJBFHFBADKBCBANJR@FA`GXBTAXBJCHHHABHFDRDDF@D"
                ],
                "encodeOffsets": [
                    [
                        123188,
                        31253
                    ]
                ]
            },
            "properties": {
                "cp": [
                    119.403576,
                    29.597459
                ],
                "name": "杭州",
                "childNum": 1
            }
        },
        {
            "id": "330200",
            "type": "Feature",
            "geometry": {
                "type": "MultiPolygon",
                "coordinates": [
                    [
                        "@@@@@A@B"
                    ],
                    [
                        "@@EB@BDLGFBDDD@DH@HEFD@DFBBAD@FHCDBJPFFDD@HABCFAD@BDFA@EDCAC@CAAMBW@CCDABCEGBCAAG@CCCCE@IDEECGCA"
                    ],
                    [
                        "@@IBAHIB@DJJTFB@@CKECCBAD@BCFACGCA"
                    ],
                    [
                        "@@@DB@H@FAFHB@@ABA@ACAACBAAAB@@AEEG@ABCABFGDDD"
                    ],
                    [
                        "@@BAC@BB"
                    ],
                    [
                        "@@@CAB@BB@"
                    ],
                    [
                        "@@BBHBDC@CGAEB@D"
                    ],
                    [
                        "@@GFAF@HBFJDJEBAJ@BCBC@EAGAAKAKD"
                    ],
                    [
                        "@@BDF@BA@ECCE@ADBD"
                    ],
                    [
                        "@@FBP@B@BECGEAK@CBADBH"
                    ],
                    [
                        "@@@ACEC@AB@DBBDBDA"
                    ],
                    [
                        "@@ABFBACA@"
                    ],
                    [
                        "@@D@AAA@@B"
                    ],
                    [
                        "@@FA@EKIGD@BD@@DDHD@@BB@@A"
                    ],
                    [
                        "@@@FBBLABCAC@EBCF@@CIA@CEE@CC@@ACAADGB@DBBDBAJBBCD@DH@BB"
                    ],
                    [
                        "@@BA@CA@@AEABFD@@D"
                    ],
                    [
                        "@@BDDBLIAAOF"
                    ],
                    [
                        "@@FB@ACAAB"
                    ],
                    [
                        "@@F@@ACAAB@B"
                    ],
                    [
                        "@@@HD@HABFHDD@BBHADAFGHBFCBCCAKDEAGDM@A@FC@AEAAABCCAEBBDABCCA@@H"
                    ],
                    [
                        "@@BA@AEA@BD@@D"
                    ],
                    [
                        "@@CD@BH@@AB@H@BCACBAB@NJ@A@CDBB@AA@CC@KCC@E@IJ"
                    ],
                    [
                        "@@@BJBDDHBBACCH@@AEA@CCAFAA@@C@AGACD@BEAEB@DB@BDF@GB"
                    ],
                    [
                        "@@A@@DHBBCD@@CBA@@GBABA@AB@A"
                    ],
                    [
                        "@@@BBDBFJABE@AGBACE@"
                    ],
                    [
                        "@@ABBBFBBAB@FAGCA@@DEA"
                    ],
                    [
                        "@@DB@BFB@DDABAACB@@AC@@CI@@BAB"
                    ],
                    [
                        "@@CBBBL@DACEAACBADA@"
                    ],
                    [
                        "@@FBFCDIM@EBCAABDFD@BD"
                    ],
                    [
                        "@@BBB@@AC@"
                    ],
                    [
                        "@@DBBACAAB"
                    ],
                    [
                        "@@@BB@@DJBF@BEACCAMD"
                    ],
                    [
                        "@@@DA@@B@BD@DEDABCDAGAADC@AD"
                    ],
                    [
                        "@@BBHBFADBBEHBFCCA@EG@ACA@CFC@ACEBAFAF"
                    ],
                    [
                        "@@E@ABPDBED@@AFA@ACAK@EDBD"
                    ],
                    [
                        "@@CB@HFAF@HACCA@CAE@"
                    ],
                    [
                        "@@@DF@DAF@FA@CCAADC@AAA@AAE@ABBD"
                    ],
                    [
                        "@@FBDDH@EC@CC@EAAB@B"
                    ],
                    [
                        "@@@BFBHEC@IB"
                    ],
                    [
                        "@@A@KBBBH@D@@C"
                    ],
                    [
                        "@@EN@BD@@CHGCCA@"
                    ],
                    [
                        "@@FECAACCA@ABACCAPHF"
                    ],
                    [
                        "@@@JDBB@@CBABCFBB@AECAABG@AB"
                    ],
                    [
                        "@@BBF@DAB@AFB@FEHAACFADECB@CAAGACBA@AB@BMJ@D"
                    ],
                    [
                        "@@D@DAJDBBDACCBEEDAECC@GEAIDEFBHF@DF"
                    ],
                    [
                        "@@BFHACCE@"
                    ],
                    [
                        "@@@EE@@FF@"
                    ],
                    [
                        "@@BBBAA@A@"
                    ],
                    [
                        "@@@CCABDBB"
                    ],
                    [
                        "@@TFH@DBHABBB@H@@CGCCE@GFGL@DAACDEA@CA@ABCFCEAAGA@ADEDEAA@IFSXADCBCD@H@B"
                    ],
                    [
                        "@@X@FB@HA@CAABMH@BJBDDCHED@DDDBAFABBADE@@DDHDBDA@A@AFCD@DADBBAACBAB@FDDAACACGEBALG@AGACCK@AA@C@EDCFCDAH@DDHBDC@AB@VHBA@AGGACACCECAABA@CGIEE@CBCAABAFA@CCA@AFG@@CDC@AEA@GACEAEBCHA@CACGC@AFA@AACBEECBABBDHFAJFBADBDC@C@ADBD@BFBF@DC@AFFDA@DD@ADE@@D"
                    ],
                    [
                        "@@ACCA@BBDCD@@FBBE"
                    ],
                    [
                        "@@BDBA@AC@"
                    ],
                    [
                        "@@@DD@BEA@CB"
                    ],
                    [
                        "@@D@BAGAABDB"
                    ],
                    [
                        "@@CBPBBA@AGAEB"
                    ],
                    [
                        "@@@FBFNDBAFB@DHBBADDB@BAHA@AKE@EIBEC@GIA@FK@"
                    ],
                    [
                        "@@F@BAEAAB@B"
                    ],
                    [
                        "@@A@BDDDDCACE@"
                    ],
                    [
                        "@@CXBFBBFBv@XGPQHA@C@ACAODAADAAIPABCACCEE@C@AA@CF@BCEEC@@ALC@CCEEBAABCAAKDEAIFDFE@@B@DDBADM@GGA@UXIHCB@FBH"
                    ],
                    [
                        "@@@BBA@AAB"
                    ],
                    [
                        "@@CF@BDB@CF@@CD@AAEAAB"
                    ],
                    [
                        "@@C@@BBBD@BCBACAAD"
                    ],
                    [
                        "@@BDHCCCGAAFD@"
                    ],
                    [
                        "@@DFFA@C@ABDB@DCAABCACABACEBEAABDHCBBB"
                    ],
                    [
                        "@@BBDA@AEB"
                    ],
                    [
                        "@@CHJAAEC@"
                    ],
                    [
                        "@@CFBDB@FG@GAAABAF"
                    ],
                    [
                        "@@h^VBTHH@JA^MFKBOAUMIaMcKWQKMcOeUGEMQAOIIYiY]QKOASIiGYAQAYMem{utaPELAlHJHVTPDL@NEHIHC`CZGHK`qRKJMBG@MEGUOAMJSLI@ACEOGcuEQHoFIZULKDSCKS_MeWEGC[WOUCYFCACCACICQBEFChKDCBE@EKQKQGUCOBSFGV@XETBHBH@JANEF@BAAG@EAKBCF@BCACWB_OAABCACMBBKRg@EDA@ACCGmAAGAg@WK@A@EX@FAHKJKXO^ODE@ECEEAI@@ABELGFuAEAEGGQCGECC@ADAT@FA@EDACCUMCEC]@GCGI@SKUFKDCBCFBZADe@QCEDCDBHTR@BCHEBMZGDSAMIIIMIKGO@SDOJORKHSHE@IEQCQDIFENQAfe}WÇvfHUAICk}GGG@gHoFOBMHSPIFKBa@SCKBEAOACBCDCDBFFFCPBHKHGJSTGDCASOMCKE@GLK@E[mEK@CFEAEDCGGCGKIOCKGKOCGG@AB@LABMDMAAAHKCE@GEEBIGAG@ABAFKBEHKDEJFD@BMHO@CJFHBNAX@PNLBBCBCCEA@B@DCBEAABCF@HGHONITAFBRKBADCHCBOBYC{FIDGFBDFFHBFJIFAHMNGRLLDRD@NAH@ANEL@HDNJLCFFF\\THJ@HAFEBMGELBBLFFFAN@JCJF@HBHJJFHHDBLBRP@P@FEHALDLBBD@@DER@JBJEFUDABBL@HBJ@JNRBD@DIBEFABBJCDLF@BCJBLR^@BEDOFADCFBDLABB@HDDJBFFEP@FIFADBDBDI@GCEAYPM@IAKDQAI@[HS@IBEFCLIF]BG@ADBPJH@FFHGN@HKCCDCAEDNFALBBHBAJHABDADC@CBCACBFL@DEDGBAJEHGBGFGAEAWJCHF^CRKLSdEBCBWOMCWKIAWHKAKDEDEJBDFDH@NDJ@JF@FOLBJDLLDRBNDHDDDAFGDIBQ@KLCH@BJNDDLBJFJGB@DDUd@DBBPFXCFANKHBNN^PDFBJLFFDHRPHBD@DEJKLDLJH@FFJBFABKHIDG@KLGBIAEBGFCHCDG@AIA@EB]XULADDHE@EDILCJGHDBJB@D@FRT@DAD@FFHJDDJHb@TRJPBJADBHFHLH@LDBDBLFHDFSHCNEFULE@GAGAIDC@EKGAEBACGLFHABFJABC@EE_ACB@DMBCFCDG@SP@JFDEfIDEJKFONBHDFBDCDITEDIDG@CEG@ORAFBHGLM@ABBDJFDDDJQlEXAN@DMPGZo_rUf¦\\j\\LxPfHf\\P`hpxjpXÀtPDÌ¡n[XCdBbL^HdE`STQho¶pelk~~hRkNUROiJKxl_H@DZA~glar[idENHAHDFnbBDZLJBFADGFCHADCFQBANADAHQHEBE@S@WDKDAFAjBPAxBNCH@"
                    ]
                ],
                "encodeOffsets": [
                    [
                        [
                            124865,
                            30450
                        ]
                    ],
                    [
                        [
                            125115,
                            30114
                        ]
                    ],
                    [
                        [
                            124909,
                            30037
                        ]
                    ],
                    [
                        [
                            125165,
                            29553
                        ]
                    ],
                    [
                        [
                            125179,
                            29557
                        ]
                    ],
                    [
                        [
                            124827,
                            29700
                        ]
                    ],
                    [
                        [
                            124949,
                            29988
                        ]
                    ],
                    [
                        [
                            124939,
                            30621
                        ]
                    ],
                    [
                        [
                            124955,
                            30627
                        ]
                    ],
                    [
                        [
                            124935,
                            30618
                        ]
                    ],
                    [
                        [
                            125091,
                            30616
                        ]
                    ],
                    [
                        [
                            124686,
                            30717
                        ]
                    ],
                    [
                        [
                            125033,
                            30576
                        ]
                    ],
                    [
                        [
                            124935,
                            30341
                        ]
                    ],
                    [
                        [
                            124956,
                            30333
                        ]
                    ],
                    [
                        [
                            124928,
                            30282
                        ]
                    ],
                    [
                        [
                            124927,
                            30270
                        ]
                    ],
                    [
                        [
                            125014,
                            30213
                        ]
                    ],
                    [
                        [
                            124939,
                            30213
                        ]
                    ],
                    [
                        [
                            124904,
                            30210
                        ]
                    ],
                    [
                        [
                            124902,
                            30198
                        ]
                    ],
                    [
                        [
                            124909,
                            30181
                        ]
                    ],
                    [
                        [
                            125117,
                            30168
                        ]
                    ],
                    [
                        [
                            125137,
                            30154
                        ]
                    ],
                    [
                        [
                            125154,
                            30166
                        ]
                    ],
                    [
                        [
                            125164,
                            30170
                        ]
                    ],
                    [
                        [
                            125171,
                            30169
                        ]
                    ],
                    [
                        [
                            125188,
                            30160
                        ]
                    ],
                    [
                        [
                            125111,
                            30112
                        ]
                    ],
                    [
                        [
                            125126,
                            30085
                        ]
                    ],
                    [
                        [
                            125139,
                            30093
                        ]
                    ],
                    [
                        [
                            125156,
                            30081
                        ]
                    ],
                    [
                        [
                            124901,
                            30112
                        ]
                    ],
                    [
                        [
                            124930,
                            30117
                        ]
                    ],
                    [
                        [
                            124932,
                            30047
                        ]
                    ],
                    [
                        [
                            124914,
                            29989
                        ]
                    ],
                    [
                        [
                            124932,
                            29998
                        ]
                    ],
                    [
                        [
                            124957,
                            29988
                        ]
                    ],
                    [
                        [
                            124967,
                            29981
                        ]
                    ],
                    [
                        [
                            124972,
                            29965
                        ]
                    ],
                    [
                        [
                            124971,
                            30520
                        ]
                    ],
                    [
                        [
                            124965,
                            30519
                        ]
                    ],
                    [
                        [
                            124904,
                            29933
                        ]
                    ],
                    [
                        [
                            124912,
                            29930
                        ]
                    ],
                    [
                        [
                            124935,
                            29937
                        ]
                    ],
                    [
                        [
                            124992,
                            29915
                        ]
                    ],
                    [
                        [
                            124991,
                            29908
                        ]
                    ],
                    [
                        [
                            125015,
                            29888
                        ]
                    ],
                    [
                        [
                            125007,
                            29890
                        ]
                    ],
                    [
                        [
                            124879,
                            29889
                        ]
                    ],
                    [
                        [
                            124955,
                            29879
                        ]
                    ],
                    [
                        [
                            124987,
                            29829
                        ]
                    ],
                    [
                        [
                            124963,
                            29800
                        ]
                    ],
                    [
                        [
                            124913,
                            29784
                        ]
                    ],
                    [
                        [
                            124945,
                            29748
                        ]
                    ],
                    [
                        [
                            124953,
                            29723
                        ]
                    ],
                    [
                        [
                            124857,
                            29733
                        ]
                    ],
                    [
                        [
                            124769,
                            29771
                        ]
                    ],
                    [
                        [
                            124708,
                            29771
                        ]
                    ],
                    [
                        [
                            124714,
                            29781
                        ]
                    ],
                    [
                        [
                            124744,
                            29734
                        ]
                    ],
                    [
                        [
                            124730,
                            29736
                        ]
                    ],
                    [
                        [
                            125182,
                            29574
                        ]
                    ],
                    [
                        [
                            125188,
                            29574
                        ]
                    ],
                    [
                        [
                            125194,
                            29580
                        ]
                    ],
                    [
                        [
                            125211,
                            29579
                        ]
                    ],
                    [
                        [
                            124854,
                            30364
                        ]
                    ],
                    [
                        [
                            124919,
                            30343
                        ]
                    ],
                    [
                        [
                            125007,
                            30608
                        ]
                    ]
                ]
            },
            "properties": {
                "cp": [
                    121.459792,
                    29.388388
                ],
                "name": "宁波",
                "childNum": 69
            }
        },
        {
            "id": "330300",
            "type": "Feature",
            "geometry": {
                "type": "MultiPolygon",
                "coordinates": [
                    [
                        "@@CBCDBNBBJ@BGAIEC"
                    ],
                    [
                        "@@GBBDDBDABCCA"
                    ],
                    [
                        "@@G@AB@FBDN@HABCAAE@CACA"
                    ],
                    [
                        "@@I@CB@NCDIDAHBHDHFHdTF@hQF@TFVA@CACCCYSUKA"
                    ],
                    [
                        "@@I@GBIJGFSDMAICKGEAQFCDAF@XDHHDPHTLJLFFLDJ@LCPAvFLAPIfg@CCGGCYKQGaEUE"
                    ],
                    [
                        "@@A@@D@BBBDACE"
                    ],
                    [
                        "@@ABDDBAACA@"
                    ],
                    [
                        "@@B@A@"
                    ],
                    [
                        "@@A@@BBBD@@ACA"
                    ],
                    [
                        "@@A@@DDB@C@AA@"
                    ],
                    [
                        "@@A@@DD@BACA"
                    ],
                    [
                        "@@@A@B"
                    ],
                    [
                        "@@A@@FD@@CAA"
                    ],
                    [
                        "@@JBBAACE@CB@B"
                    ],
                    [
                        "@@@BJ@@CCAED"
                    ],
                    [
                        "@@DBD@BA@AGAA@@D"
                    ],
                    [
                        "@@DBDCE@AB"
                    ],
                    [
                        "@@BDF@BAECC@@B"
                    ],
                    [
                        "@@DDDABCCAC@AD"
                    ],
                    [
                        "@@BBB@@GA@AF"
                    ],
                    [
                        "@@@B@BFBACCA"
                    ],
                    [
                        "@@KFMLA@@CE@sVAAACNQDIAAIBSTOHAFFFDBJCD@GVBBNAFCJA@DIDADDBF@HEVEBABCDGBEFCN@DAHIBACC@ANKAAE@"
                    ],
                    [
                        "@@HEGIGDIJHDJA"
                    ],
                    [
                        "@@LAFGC@KDCFB@"
                    ],
                    [
                        "@@C@CF@BDBXEDC@ICAE@ML"
                    ],
                    [
                        "@@PGFEAAMCE@GDBHEHBBD@FA"
                    ],
                    [
                        "@@CFBDDANA@A@ECAA@EDC@"
                    ],
                    [
                        "@@F@HABAAAB@@CB@BCC@ABC@GB@DEDDB"
                    ],
                    [
                        "@@@FDBDAEEA@"
                    ],
                    [
                        "@@@DFDDBBAACIC"
                    ],
                    [
                        "@@HHBAD@FAB@IEIBA@"
                    ],
                    [
                        "@@GDAHBLFFfRXJHBJANCBC@EACeUQEOESE"
                    ],
                    [
                        "@@@@BAACGABDDBBB"
                    ],
                    [
                        "@@B@DACAAD"
                    ],
                    [
                        "@@GC@AC@DDHB"
                    ],
                    [
                        "@@DFH@ACIA"
                    ],
                    [
                        "@@DBD@LDDAACCABGBA@AACCBACAAC@EEE@AHC@@B@BHFAB@@A@@BFF"
                    ],
                    [
                        "@@CAA@FB"
                    ],
                    [
                        "@@DBHABEAACDGB@B"
                    ],
                    [
                        "@@FDD@CECACBBB"
                    ],
                    [
                        "@@SCAJHBDALHAEDA@CCA"
                    ],
                    [
                        "@@B@@A@IBAHADIFAHN@DGD@DDFDBFCLLLHBD@DGFB^ABJLDBBFCF@DFFAHDBJAB@DL@DCF@DHP@BGLBNJLL@BPHFJANDPBHBD@LKD@B@DDF@PKFKHICCBEDCNEHDNEJAJMNCLENSPDFERABFFFF@JCFGDAD@DDVB`@LAHBFF@BANBFEFEL@BFBDFHFFEF@HEFDNDCH@FOP@DFBHBNJJAFEPCLDXBHHLBHJB\\HJDBD@XON@JBJJJDNCFGHADACMDKD@HDJ@D@LGLBJKJALJFEAKCEBCFED@nKDIBKHGPIDGCEEKIKAEDEHIHBFGH@JBNK@E@G@EFEFCFG\\CH@JEJ@PBLDDHDFZTF@\\CJEJCFHCHADNFDA@GACAICEAEHEHOJ@H@HCH@JBFCDEHA@EJADB@JBBH@HAJDDCDIL@BFDDBBFABDDDF@LELAXDR@JFBBAJBHDFHDFHFL@F@NJNNJHPDDHCH@PGPUTBDBFBDAACBCF@DDHADA@ADELGJKFA@KAEDED@HQDMF@BEH@FAFA@K@APIF@FCBAGEFEBKDC@EFGTBDCBEEAEM@CBCB@JBPAZQHALIAAKCAABGIQ@IMCWBCCKI@ABADA@CMCGAEFAGGAHKLIDMMkBGDB@EGDEMMUq}eGECGICG@IAW@UCYA[MYaigaW]gQmK}SkoÄ¥PGXCpBdJjRNDPBLAHCBC@GC[@IBEBCHEfCPCFEFMDO@KG_IUGKGEKCU@SDEAACA@@CCE@CCIIGBAACGCA@@BA@C@@ECCABCB@FABBBDBABADC@@DH@FFJABDAFBDD@BCFDB@CBJF@DBBKB[EO@cBQFK@EBKJ]XK@CIBEDOVmRSB±KAM@KHsGQMQk]iOY_OUkkGGUEGCCGDaLIhHEXADABCDWFQHIDCLCHEBC@KAEewKWEMAGDc@iCYEMIIQKMEY]GGGGAGBOFQ@ECGIIKGSi@EDCfQDE@CGUOOKSCMAkCQMaSOKGQE{KE@kNG@EAafEBGAAB@HCFQJCJDFADMHCHQB@BFFAHIJHF@DABI@CBLFCF@DJHHP@BGHUNAFHJRLJ@FGHCJDDFBHYVEDKJIPCZ[VIJIVGLCBIBQLAFKJ@FFL@BAFQHCHBDDDAF@BHJFNCHGLKJQGG@MFABHF@DADGDEC@A@GCIBGAAGBADCEI@MHEBICIIGCG@CBMXKLCF@FDFHF@P@HCFWNC@CIQKOCCGIAACEBCCGBEDKLC@KAG@UME@AAKFI@ADEBAAE@cCOEEEAEDGFEDIAIEGIAEBAFEBGBUCQGCCBUECI@MMKACKEEGACCIUK@CEAKM@SHO@CDBF@HOPELMA@PAHEBUFKE@IAAO@QEUCGCAGBCPFBA@CEGCCQIEG@CCECAK@CCBAJ@BAIG@ADECCBCH@DKACODGBGAMBCABCCAKJG@C@C@GACCAGE@GAIFA@@EAEA@ADGBAG@GECCDBHABMACB@DNHBBABM@IDGCCDGFCFCBGCOQJILACMCAMDGAG@@BEBCA@GCAKDGLSJKDCAAKCCSDIDE@A@EFFHAVBFB@DAJKLHBFABGFGBG@GFAF@DDHCHC@M@GFI@AFCNOFLNJH@FEDME@JANIBCDCDBFIDCHGDO@EBADBJGFCFBDALCDG@GHI@IPHFJCDD@DNFBNDDCHNJGNFJCHFB@D@BEAAD@FHDAH@HKDABBPJH@FEDGBCLBDURADDDGBCFAA@ECAEBOAIEC@BDCDGDDJFHFLBDD@D@@PJN@BCFE@wHIFKAEBAJ@PCH@HDF@FEFCHBLDBFBHFBBHCBB@FDHFDDJ@BGHGNADFFDNGHE@CDLFDDHZFDHBDH@BEBCD@TEHFNL@PHBBBFFBHHHDBDBLBJJF`PF@DATFHFJNDBRADHFHRPBDJL@DEDDJ@@BCDCDFJBJLDBDE@I@EBARAFD@DDJCB@DFD@BGH@PDFPH@FIBEF@Z@DHLADEFAFBDJFN^FRCJE@GHEFBLEDNNHBJHLBH@FCHGNIR@FRLNPH@BghDJZJJAHBJMDIDADD@PBDAH@DTPB@FIDCT]DAD@FFJBHAHDJHPHJJdJFANDHABDBBDCFI@CDC@GGEDCGMBEAKBAHEFLDAHBBD@PMFAJANDHNFDJBj@DBDH@DGHBFFHNHB@B@DIL@PNFBBBBJDDB@@CLBXBTCDCF@HCJAFBDFB@D@JCD@B@FADFNBHCFGBE@KAKDA@KJELCDEBB@ADA@EDCFEHAL@NAHBREFCRDFD@D@DHJBHAJFXPFHA@ACGFEHAL@LDfdN@JBHAVDHABADQ@CPHJNDHPFCHGBQBCB@DBHBFJNFZJF@ZAFGFBHDD@FBDDBH@DADALDFABBJFDPAFCFAHKFCB@H@BHBAFFHPHNDHAF@LJDAJPTTAHIFADFJADCBIDADSFIF@HBBdPNDPAFJCDAHCDCFABBFDHJFRDBFCJEDAFQFCAC@@LBLDHLDFJHLJJBBHDBBGTCBGBIBEJJR@LI^EFAFALCRYFEDIPK@UDINBHADOBMEUHAFRFLNAN@D@B@JCJABKDQ@OH@BBFAL@FLDJLAFCBEACBEHCLADBFLBBD@BABADBD@PFFFDHCRATIAG@ARQDB@FDJFLAHBNGLEDCFAHNNLB@FBJAFBD@LFD"
                    ],
                    [
                        "@@B@@CCBBB"
                    ],
                    [
                        "@@@@@@"
                    ],
                    [
                        "@@@@@@"
                    ],
                    [
                        "@@LDD@BC@CFA@GDACGKGQ@@DGAEB@BDFJBBBAFBB@DDD"
                    ],
                    [
                        "@@JDBAAACCED"
                    ],
                    [
                        "@@ABD@HDDA@AEEGD"
                    ],
                    [
                        "@@DBBACAAB"
                    ],
                    [
                        "@@FBBACACB"
                    ],
                    [
                        "@@DDDAHBBACEDC@AEBKC@L"
                    ],
                    [
                        "@@DBDDH@BCHA@GCCQECB@DA@@BDDABA@BD"
                    ],
                    [
                        "@@@FDBFBDDDEJ@@CJ@BAC@@CA@IA@BKCGBCA@F"
                    ],
                    [
                        "@@D@C@"
                    ],
                    [
                        "@@@AEDDB@ABA"
                    ],
                    [
                        "@@D@AAAB"
                    ],
                    [
                        "@@BBBCC@@B"
                    ],
                    [
                        "@@D@DAGB"
                    ],
                    [
                        "@@@BB@B@AEA@@D"
                    ],
                    [
                        "@@@BD@CA"
                    ],
                    [
                        "@@FFHBEECAC@"
                    ],
                    [
                        "@@CD@DJ@DAACCAC@"
                    ],
                    [
                        "@@JRHB@EDFD@MUIC@DAB"
                    ],
                    [
                        "@@B@BADDDBAHH@ADB@HBFCFDDABCIGAEKIGAECGAABBBABC@AFGABDDDBAD@FD"
                    ],
                    [
                        "@@FHH@JAACEEB@ACDB@@@CCCE@CDDDAFGE@B@D"
                    ],
                    [
                        "@@BBD@@IECC@BJBB"
                    ],
                    [
                        "@@NB@CD@BCCAE@AEG@ADA@AHB@DA@D"
                    ],
                    [
                        "@@BBBAACAD"
                    ],
                    [
                        "@@DDB@EC"
                    ],
                    [
                        "@@BBFBB@DDF@AABAACC@CCC@@BC@A@@B"
                    ],
                    [
                        "@@B@CABB"
                    ],
                    [
                        "@@FBDAFBBA@CBAGAODDD"
                    ],
                    [
                        "@@DFFCA@CCC@@B"
                    ],
                    [
                        "@@@BJ@GAA@"
                    ],
                    [
                        "@@HFFABAEGAAEBBBCB@B"
                    ],
                    [
                        "@@DBDCBACAE@@F"
                    ],
                    [
                        "@@EL@BABAJFDLA@BHDCDBDB@DCD@DE@CFAACEADIEECAKIICC@@BDDBF"
                    ],
                    [
                        "@@C@@DDBBFFBDCBBDACAAEDCDAB@CEA@GHGB"
                    ],
                    [
                        "@@@BDDF@HDB@CCCAAEC@EB"
                    ],
                    [
                        "@@FBF@ACAAI@BD"
                    ],
                    [
                        "@@JFHBHABACEI@CC@ECAA@ACGC@DBBBDAJDB"
                    ],
                    [
                        "@@@FB@JI@ABA@AGAAD@FCB"
                    ],
                    [
                        "@@BBDAFDDCFABCHCBICAGACDC@AB@DAFEDC@ABBB"
                    ],
                    [
                        "@@HHLDDA@EE@IGE@AD"
                    ],
                    [
                        "@@@@@AABB@"
                    ],
                    [
                        "@@B@A@"
                    ],
                    [
                        "@@B@@AA@@B"
                    ],
                    [
                        "@@@@BAAA@D"
                    ],
                    [
                        "@@DDDC@AE@AB"
                    ],
                    [
                        "@@@BB@AA"
                    ],
                    [
                        "@@A@@BFBBA@AE@"
                    ],
                    [
                        "@@A@DDD@DAAACBCA"
                    ],
                    [
                        "@@B@@AA@@B"
                    ],
                    [
                        "@@@B@BDEA@AB"
                    ],
                    [
                        "@@DBBA@CCBAA@D"
                    ],
                    [
                        "@@E@DDBC"
                    ],
                    [
                        "@@FD@AEA"
                    ],
                    [
                        "@@DADBDAEICAE@CAEBE@BHLBBDD@"
                    ]
                ],
                "encodeOffsets": [
                    [
                        [
                            123981,
                            28693
                        ]
                    ],
                    [
                        [
                            123949,
                            28698
                        ]
                    ],
                    [
                        [
                            123960,
                            28692
                        ]
                    ],
                    [
                        [
                            124095,
                            28635
                        ]
                    ],
                    [
                        [
                            124005,
                            28609
                        ]
                    ],
                    [
                        [
                            123812,
                            28483
                        ]
                    ],
                    [
                        [
                            123801,
                            28481
                        ]
                    ],
                    [
                        [
                            124061,
                            28478
                        ]
                    ],
                    [
                        [
                            123747,
                            27716
                        ]
                    ],
                    [
                        [
                            123759,
                            27710
                        ]
                    ],
                    [
                        [
                            123749,
                            27703
                        ]
                    ],
                    [
                        [
                            124058,
                            28470
                        ]
                    ],
                    [
                        [
                            124037,
                            28394
                        ]
                    ],
                    [
                        [
                            124034,
                            28345
                        ]
                    ],
                    [
                        [
                            124085,
                            28361
                        ]
                    ],
                    [
                        [
                            124101,
                            28366
                        ]
                    ],
                    [
                        [
                            124096,
                            28393
                        ]
                    ],
                    [
                        [
                            124055,
                            28441
                        ]
                    ],
                    [
                        [
                            124072,
                            28577
                        ]
                    ],
                    [
                        [
                            124130,
                            28512
                        ]
                    ],
                    [
                        [
                            124128,
                            28505
                        ]
                    ],
                    [
                        [
                            124014,
                            28103
                        ]
                    ],
                    [
                        [
                            124001,
                            28154
                        ]
                    ],
                    [
                        [
                            123964,
                            28144
                        ]
                    ],
                    [
                        [
                            123985,
                            28088
                        ]
                    ],
                    [
                        [
                            124020,
                            28133
                        ]
                    ],
                    [
                        [
                            124035,
                            28128
                        ]
                    ],
                    [
                        [
                            123969,
                            28103
                        ]
                    ],
                    [
                        [
                            124180,
                            28680
                        ]
                    ],
                    [
                        [
                            124173,
                            28672
                        ]
                    ],
                    [
                        [
                            123959,
                            28680
                        ]
                    ],
                    [
                        [
                            123950,
                            28651
                        ]
                    ],
                    [
                        [
                            124132,
                            28608
                        ]
                    ],
                    [
                        [
                            124137,
                            28601
                        ]
                    ],
                    [
                        [
                            124081,
                            28591
                        ]
                    ],
                    [
                        [
                            124033,
                            28585
                        ]
                    ],
                    [
                        [
                            124020,
                            28589
                        ]
                    ],
                    [
                        [
                            124156,
                            28503
                        ]
                    ],
                    [
                        [
                            124159,
                            28502
                        ]
                    ],
                    [
                        [
                            124122,
                            28481
                        ]
                    ],
                    [
                        [
                            124134,
                            28486
                        ]
                    ],
                    [
                        [
                            123278,
                            29163
                        ]
                    ],
                    [
                        [
                            124053,
                            28458
                        ]
                    ],
                    [
                        [
                            124042,
                            28453
                        ]
                    ],
                    [
                        [
                            124042,
                            28454
                        ]
                    ],
                    [
                        [
                            123990,
                            28459
                        ]
                    ],
                    [
                        [
                            123998,
                            28468
                        ]
                    ],
                    [
                        [
                            123999,
                            28473
                        ]
                    ],
                    [
                        [
                            123908,
                            28504
                        ]
                    ],
                    [
                        [
                            124062,
                            28421
                        ]
                    ],
                    [
                        [
                            124054,
                            28427
                        ]
                    ],
                    [
                        [
                            124039,
                            28429
                        ]
                    ],
                    [
                        [
                            124039,
                            28437
                        ]
                    ],
                    [
                        [
                            124069,
                            28411
                        ]
                    ],
                    [
                        [
                            124072,
                            28413
                        ]
                    ],
                    [
                        [
                            124077,
                            28409
                        ]
                    ],
                    [
                        [
                            124081,
                            28412
                        ]
                    ],
                    [
                        [
                            124082,
                            28415
                        ]
                    ],
                    [
                        [
                            124051,
                            28359
                        ]
                    ],
                    [
                        [
                            124106,
                            28316
                        ]
                    ],
                    [
                        [
                            124100,
                            28315
                        ]
                    ],
                    [
                        [
                            124105,
                            28326
                        ]
                    ],
                    [
                        [
                            124114,
                            28273
                        ]
                    ],
                    [
                        [
                            124109,
                            28288
                        ]
                    ],
                    [
                        [
                            124127,
                            28277
                        ]
                    ],
                    [
                        [
                            124041,
                            28288
                        ]
                    ],
                    [
                        [
                            124077,
                            28294
                        ]
                    ],
                    [
                        [
                            123953,
                            28296
                        ]
                    ],
                    [
                        [
                            123952,
                            28301
                        ]
                    ],
                    [
                        [
                            123961,
                            28297
                        ]
                    ],
                    [
                        [
                            123948,
                            28334
                        ]
                    ],
                    [
                        [
                            123843,
                            28327
                        ]
                    ],
                    [
                        [
                            123834,
                            28319
                        ]
                    ],
                    [
                        [
                            123828,
                            28313
                        ]
                    ],
                    [
                        [
                            123836,
                            28308
                        ]
                    ],
                    [
                        [
                            123840,
                            28303
                        ]
                    ],
                    [
                        [
                            123876,
                            28314
                        ]
                    ],
                    [
                        [
                            123806,
                            28359
                        ]
                    ],
                    [
                        [
                            123819,
                            28350
                        ]
                    ],
                    [
                        [
                            123821,
                            28346
                        ]
                    ],
                    [
                        [
                            123725,
                            28310
                        ]
                    ],
                    [
                        [
                            123740,
                            28336
                        ]
                    ],
                    [
                        [
                            123727,
                            28351
                        ]
                    ],
                    [
                        [
                            123711,
                            28355
                        ]
                    ],
                    [
                        [
                            123652,
                            28245
                        ]
                    ],
                    [
                        [
                            123639,
                            28233
                        ]
                    ],
                    [
                        [
                            123638,
                            28233
                        ]
                    ],
                    [
                        [
                            123632,
                            28225
                        ]
                    ],
                    [
                        [
                            123617,
                            28215
                        ]
                    ],
                    [
                        [
                            123603,
                            28182
                        ]
                    ],
                    [
                        [
                            123603,
                            28186
                        ]
                    ],
                    [
                        [
                            123602,
                            28183
                        ]
                    ],
                    [
                        [
                            123588,
                            28169
                        ]
                    ],
                    [
                        [
                            123737,
                            27693
                        ]
                    ],
                    [
                        [
                            123733,
                            27693
                        ]
                    ],
                    [
                        [
                            124137,
                            28613
                        ]
                    ],
                    [
                        [
                            124137,
                            28613
                        ]
                    ],
                    [
                        [
                            123799,
                            28377
                        ]
                    ]
                ]
            },
            "properties": {
                "cp": [
                    120.502111,
                    27.800575
                ],
                "name": "温州",
                "childNum": 98
            }
        },
        {
            "id": "330400",
            "type": "Feature",
            "geometry": {
                "type": "MultiPolygon",
                "coordinates": [
                    [
                        "@@DB@ACGA@ADDD"
                    ],
                    [
                        "@@@@AA@BB@"
                    ],
                    [
                        "@@@BB@DA@AC@AB"
                    ],
                    [
                        "@@B@BAE@BB"
                    ],
                    [
                        "@@ABBDFAACC@"
                    ],
                    [
                        "@@R@@IBCPFPEBDH@FCHAD@@BILBB\\BDLEBBFCBBBDADBD@HADMHABAEEBAh@BCN@CAFIAABC@@@CA@@CB@@GCABCHBBEAADEB@DQB@D@@CCA@EA@@AMA@AAABCA@@CD@@AAEDGE@BGD@BGB@@KAADEFE@EAkAIDBH@@EA@ACGB@CG@CC@CCGDCBG^CBAAE@AHAJ@DCDC@@A@ACFACCDACACDEEFAACEEDCCCB@ACCBBCCCHCCCEBCEC@CGE@CECBAEBAA@ACE@EGACHAGEHECEHABB@DBADFA@BDDBBA@ADAB@ADBANNFBBC^ILQDKPDCHA@ADA@BEC@CB@@DBBHB@CFHBDEHAEN`LCLD@CDHDFD\\@dPAAB@@A@AD@AABADCD@BALDDFBABCJCDBBA@ABAEGAKCCB@BBB@TCBDFEACBA@CDA@DB@@IIKGQCa@IC@I@CEJMZCHD@ABAFBBDRAFCDBFA@GFDLBBBBCDABCLDFBFD@DDBDABDBCJKHBCNDFJDX@BAHOBADBB@@GDAAADEDGBOJEAABA@BDABBDAAABABBXKDATSB@BBDCB@ACBEAAB@AADECE@EECBECEBEB@BIDAAEDA@GF__CCCYeIKOIUGMaOk[AI@KAAYKKBECIGKGSwW\\kluvuhaOC¿soWwigoO_e[eG[i¡[Sq@WBTSBKFiXQRIXAl@\\AnELGHEBQFPYBÇA¿BO@M[GOIg@IKQMNGBONUL@DKJHVCBPZPBJH@NAFiGaKSAOKCHGD]JKB@B@REJMACDADHFJBNH@FFHPL@NCFTNALDDAPEDANBLFDBLKAGEC@AJEL@DDF@NCP@DELEXCHE@EAWAAB@DFNA^CZEJ@FH@HDJBFFHDFJ@FCF]\\BN@JLH^@PDDBN`@JHVEJBHBLJDPADCDELED@DFFAJBHBDFHPDFVFL@xHNDV@JBAFCFIHIDCDBFFFLAXBJDTR@DDDNXAHEDADAJELCNKXL@RCBBF@JCXG`dpHNNRHHBHJHbTFJLHBANEXCRDRLTCPBB@AEBANEFA@PFD@LBFB@DCDENRFLNDFJBBDC@EPGAA@EHADCFBDDBDGPBFXDGjDNBPEZGPOT[JHJTVNIDBDHDBHCXBLEHIDAP@HFRRXF@DCRDRB@BAFAFFBDDBnJdBhQDIDADBBEFBHFFCDCDBBADB@AD@@BD@@JL@DBJB@BVJBNFB@LJ@B@"
                    ],
                    [
                        "@@BDD@ACC@"
                    ],
                    [
                        "@@BA@@A@@B"
                    ],
                    [
                        "@@@@A@B@"
                    ],
                    [
                        "@@DD@CAAAB@@"
                    ]
                ],
                "encodeOffsets": [
                    [
                        [
                            124055,
                            31333
                        ]
                    ],
                    [
                        [
                            124038,
                            31327
                        ]
                    ],
                    [
                        [
                            124036,
                            31322
                        ]
                    ],
                    [
                        [
                            124035,
                            31314
                        ]
                    ],
                    [
                        [
                            124227,
                            31209
                        ]
                    ],
                    [
                        [
                            123803,
                            31762
                        ]
                    ],
                    [
                        [
                            124249,
                            31232
                        ]
                    ],
                    [
                        [
                            124252,
                            31229
                        ]
                    ],
                    [
                        [
                            124251,
                            31225
                        ]
                    ],
                    [
                        [
                            124216,
                            31239
                        ]
                    ]
                ]
            },
            "properties": {
                "cp": [
                    120.750865,
                    30.462653
                ],
                "name": "嘉兴",
                "childNum": 10
            }
        },
        {
            "id": "330500",
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    "@@DQLOTMFGBGAK@INe@EEA@ADBDALSPORYZSLKFUJMDWDCdU^IhMja^QvqfW@AFAFBH@BAFABCFCINCDCRD`E\\CLB^@^DH@PB\\BXD^FRFZDxR@CAEUUBIDG@EGCCQ@CDK@EBMCABEAANOPD@FJ@DLJ@V@dHLHLDMpBBDDF@XMFK@MBEFCBAACKEAIAGBCJANULEBCACUMAILGDAJADKJG@[@AICACBIBCJAFKJCJ@BCDGAOBMHMLQDKE@CAQDK@LWDMFKBIBCFCBGMWCC@CSQICWAKBEEAEDCJCJGDEBEIAU@MCwGK@UECEGOCEGAIAEBCEC@KFCFCDOBICAKAGFIGU@IM_CAOC]@KG@OAE@E^WDIEKGCEEIAGCG@@EFIBGDoEMBICEQCECAGGBGGIDWASBWA_HEBQ@MIABADCLABGEAEBIWCEEBCAA@@HCMECDGAJGAEFEACIFA@@GDEGEK@EACEUEEJBNAFGBiGOEG@ABEHODCDAHHJADeDCAEAOBE]IKAEBOAOFKFCFI@GCGGCFGAAMAMCG@AFADEBUDM@WBGFEJC@aDGAOKIKAAGAKBGDEJ@FGHIBIAGBEDAPCFGFG@EAQIC@IFCAEEE@GBMFUBAD@JDHLF@DEDE@IAEBCJIFKPERA@ABCAAGICI@GDEJUNE@cIGAUNcFIHBBJDBDB^FRAFCDa@GAI@]DORGHKDGKGCCAOBAA@CD[LWHIDI@IFMAU@CGCHM@EKWAICEIA@I@MPODIFEDEAEAAUGECOMIQ[SKCG@OCKBGDOD@BDBDD@FCPER@FFDXDAPIFEBCAOOSKMAKBQIIASDCBMNALEHEF]GIICGQMAGDKAECCIAMGICGA]JODM@MAS@WHGBACIWKOI@CIECICGEEEWEG@@BEHKJWDUAGBAFDXCNKHSCEB@LHJBJGNBNGFSHABDPAJCH@^ALEHFRFVELIRALBDAF[CGCEGgYGAQAE@UPBPA@IDEDU@EFAPAFAFBFLFBH@HBBTLJJHBBDAFBJIJMD@FDDABSLIHAHDFJNHDLKF@dFF@LCN@PHZDVRDDBHNXBHTZLFHAFBLLHBHJFBNADBHHFDFAJMHgHMJMHCDATBHBL@VNHJH`LNPLbjAtEJBFJNAFIL@HDJ@JAH@DHFPBHGJEN@LFL@LFDFRbLPL\\NRJFDBNAJ@FBBD@HCFCLBRGHGLMRAFAJDT@FEJ@DLR@RDFPHTN@DCF@F@FFNEV@HBD@FBDDHJLRLBFTHBFPPNFHFHLFJEb@VHdGVCVBFHLPJHBFF@D[JULENDPNBPH@JHPHFFFPDFFFB@JBBRFL@JOTGPIF@HDFJFRFDP@RDLDD@HGF@LDDANFH@NJFBHAJCDCHADCBEGM@CDEFAHDFAJOH@\\JLJ@FCDGD@FHLHCLBJID@NAJFHCN@RKFCJBDBLDRJ`@HB"
                ],
                "encodeOffsets": [
                    [
                        122798,
                        31919
                    ]
                ]
            },
            "properties": {
                "cp": [
                    120.102398,
                    30.867198
                ],
                "name": "湖州",
                "childNum": 1
            }
        },
        {
            "id": "330600",
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    "@@Ve`qpHYNO@CBMFWRkCICCIEACBAN@HKAGBEPQH@DFH@JCFCJSDCACCEAGPMLEFIJCFeEC@ITOH@DCDENA@CDA`BFFD@BAEIBAEGHKBDFAHBFLD@JCHBHBF@VKFEDMTGCEEGAKACKCG@GKGECAIBOAQI@SGaCIICEG@EBC@CQS@E@CIACAHGDIJKFCF@CGBCVK^WFAB@BJH@DCDGHEFAJBHALKH@JCLGBAAEEI@EIGCKLKFI@CACOGGQECKEAICE]OMMGAMLEBWDOEAA@CVcCCA@IHIEKACCIM@ADGLKR@JAHCBECCGCMCQAKCCKAIPK@EIEI@MCG@ECACFIFCLCLBXGJBXLNDXPDAFATcLKDQE]DGXIFBHBHEHAFGBIHAFC@CEKDADBDAD@BCACGBBIGAAABKMEFCDBDCLD@GHMEG@EIGAOBCH@^AJEDKFEJAT@\\GJ@RBLCJBN@ZOFBHDJ@ACACBCJE@EFOEEIACC@GAAKBACDEBCPEFC@AQ]AKDI@AKEDCAIBAFEJA@CACMQ@IAI@GAKBAVCFEAI@IFQ@CC@AACKBKFG@E@OQOKACAGGIEGIGAE@DI@IBI@CEEKDEFIFEECGC@K@EBCB@JBLEJKOICGBOJKDI@KCGI@E@GFKASCIGAG@[F@HFL@DCBU@YFcBGEGKKG_EEBCD@JAFQDK@OOGCMAWAGAI@EA@IIOEUCAA@KFGJaDADCFKLEBOGGGAQBUECOECAAGBKLMFYAACAKBKAC@OLC@CCC@CDKPMBCAQMMQQISAQFG@cKWEGNFLBHIrFJBJAB_HCDAF@BVVJJBDADUNIBCDG@OIGA[@CCGKGAGBEFENKPLZDRALC@MIS@caEBEDWLE@IMGFSDMHMAICKDKAMVEFCBE@CAIOEAEBCFBHDFHL@DOLGHE@IAEBCHJL@DQXC@OAEDOPKBIVIHEH@fFTBHJDDFCDGRCDOACBOEBNAF]RMPIF@EACICGGMC[IOBGCEEO[GOCCODKFI@MBGAKMQCCECQDGJEFUAESBeICCCCKEAEAOMYQAIKGMWI@AFGGCE@EBEJQFKJIPANIN@JFLJFRZBbFJ@FABSRGDKPBRHRHFTFFDAFIPEDK@KEOBGAGHFJMNABIAQDABEPKDGBKFABJLAFIRCFG@MCMD@GCKGGCEGEGOCCGAGGECGAKEK@GAW[I@QFURG@KKE@WJABCNBBR@BD@LJV@BIH]@YJGJGDBJFHQHCDENUIIFQBQDCD@LDFCVJXLJDPDDH@F@LCD@LFHN@FABOHG@ELKFBHRFFFBP@DCDCDGB@ABGAE@MQKMBWLW@CNCDOJKNBFAXIJODEDK@GHEDEBGDIAECAABCHEAACAEDGAE@MN@BBDGL@FBHADKLGBCPAHDHSLCFABDH@JD@HCRMF@LDBADENCBCBEDALJHBPJFBZAD@JJBFNFH@BMBALCBAHCXDPD@HBDFBJBDDDDD@F@BD@XNLCXILBHJNDJXD^CVLFBFCJKJEFCFBNNCH@HR^RLHBRLJNRRHNBJ@FCHDD@JBJBBJCFBBHLRD@JCFE@GHAJED@FDPVNL@BGJ@DPFLLPFLEZAHEF@FBFLDBHEDCHO@MRIHBHBDBHJDNDDFCFADA^IPTHD@NLHDDNHDJ@JHRZAHDDHEHBFCF@FDLKN@NKNKD@BBFEZEBIAGBMRBFNHDHHF@TADGFDNBNAFCHCDKBYRGAIKIEIBIDCH@HJFFJJFHPC@G@ADLJNFFBFEDODADDLEHJFJJH@H\\@BBCJ@HD@JGFHDBPFV@BBFBDCDMFEJE@CAEBAN@BAAMDADBFFAbH@@AFBBDBDDA@AC@BABC@@BFB@@C@B@CAAB@BAAABBDCCEAIBEJAbFB@BRDDDJN@BBDDFBAPFPPBHCHHbGHGHKHCPCN@JDdCH@JEDADGB@D@JF`@FGJADBRHLBBBH\\XldvBFv`r|zrdSLETASXAr@T"
                ],
                "encodeOffsets": [
                    [
                        123768,
                        30999
                    ]
                ]
            },
            "properties": {
                "cp": [
                    120.582112,
                    29.997117
                ],
                "name": "绍兴",
                "childNum": 1
            }
        },
        {
            "id": "330700",
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    "@@LMPIDCDMX@RIJCJ@PJBPBFAH@BHAHG@EAOIEMCAGLEFKH@PGBA@EGMKEC@KDE@G@CCCOKIIWDUCE@KDCRCRAJEVJFMDCRGEGAIHCHIZI^@JG@AIU@KACQ@AADMBAXIF@LLH@VQREJ@X\\HBL@LFHBFDHHHBDDHPHFDFHHDL@HNCNDH@DEJQBEIKBALEHALCFOBARCJBBANMEIHGHBPALFL@FCJOBEECSEGEGQAQLOHCTQBA@EEIAaQYIEEK@IJMBMJOLIREHKH@HBBBEH@BXJHNJLRBNZBPBFLFDDDDfJTABFEVIFCHDRDFRDLNHBNAJ@LEPCDDHPP\\FFHDPA\\JNDHHJDBD@FJENO^QBEAMPFDAPBDCHQDCCEICAGES@eFGJGJULAPOFCPBD@RW@CIKDGFAJBF@HGPK@CGKCEAGDEFAFBJPDBF@DAFENULBLCJDNBNGTCHEJNF@XKFCFAdbT@NJD@BKCQKYLOFMFEHAHBHLDD\\@HBPJH@DCJAVMBCACIIUU@ABEDC`GBAAIEIJqAGEKHMNIAAKI@IGE@AJKOKSIEECICC[UQGMMGMIAEI@ALODIDAHHF@LEHMPA@ICCIEI@IBIJA@IUIIGIQCMKAEFIJEDEDGAIEI@GUQBARKACCCGBAADSNOHCDDDVBBFBFCBMDCJA@CEIAKDAFFB@DG@KDKGCG@@ABCD@FIBICCOC@CCEEASBKACH@FA@EBKESAGGAEBUEOAEICGMAE@KHIBEAMGEEIIEIImIK@KGMCCBIKICIECEACKKQCGGICS@QJC@ECIBABCF@HBDD@DDEDA@MAEBIJDFIHCEEGBEAMKCMACCAGPQCCGAACFCAEGBMCAA@ADGECCCBCBCGGAAGFBHEJKDKCEBSDMAQGGIGACJCVGJCACGOCCH@JEDECEIECAEDC@CAKGIE@IJKAQJQB@FCHEB@FE@CBANQDEF@DGHSHIH@@BHALIBQJBDD@DD@VDFHHBFAFGJEBADDJ@DGCCBIAQBOEE@ADBHCDAJCLCBIICABE@CECE@GI@AHIGIIODAFAL@BAAECC@CFKAcBWCEYGECKOCMQOWIAMEEKMIKCKBCPKBCEIMKI@ODG@AE@ACCCIEAS@AFCBQDOHMAAAACHIIUIII@KBEFMAAB@HABG@OBQRBLDBABCDIAKCIIGCg]WCQEELIDIHKD@FBFAHIACDMFGHODCDAHGCI@CAEKICIFKCG@CFIFK@OHKAA@A]KEBGACOIGICIBEAAEGOKG@CHCBICKKDGBCAGCEKUAA]AGACACKKEQQWMACAEA[EO@EDE@GGKIIOSQGE@MDMJIFOAIEEYp[BG@GIKAGAEAACBKFGBU@GAAC@KCCGEKMMKCG@IAESQ@KCGCCYEQAO@[T[FCAAAKWEEK@_DKAWAIDC@IGU@@BAHGHm@E@EBIT@DBF@JCFCBUDOFE@ECEOECCACAEDAH@BABDB@TDNCH@BFLJPFDDHDJAVGFaTEF@NEDM@OIG@EDK\\@DFDHTARETBJFLBRBHAR@PCT@TDDPER@MTALBLAFABIDEAOIMAGEWAQICCA@IBEDCVEDGDIPGB@FCHMHS@KCCSCAMGAC@GCEIGM@GBGFGXMNAHDbABI@@FDLDFZHFFBDADQVBHDD@BCFNB@DMLC@ECCIAAGBI@MGABFbJPFDF@HIHADDFRCDOJADHBXEFHBL@RIJMFGTED@JGRGJEJCTEPKHAF@DDBV@JHHJFJAHGD@HDDADEFAFLp@RBDDABQDEBCBADDATEN@FBLBDIHCXBDFFBHEDGRCDICKBKCC@EDCFDTCDOHKPEDOFO@A`ABABUFEF@NDF@FKFKP@FFHEHDNCNGDODABHBDTAJDFCH@HVPHFFJDJFFJFTHFDDJFDFBBHBBHBBDCLAJFBHBLE^@JBJJBHAD@LBADEF@@D@JKL@DBBbNJBFD@FADEBHT@FELILG@CBCJHTAFBLHJADBFADEDAFCDIDAD@DHFLXB@LED@TDHLD@NADDPZHDB@JCJeN@HIBA@IBAD@FFD@F@FBPDLTGH@FTDBE@KFEAGBCBCLGFGDOCGBGJUEIJQDKFCJBDAJGDG@KBCXCD@PHD@PCFJTXDJDJAHCDLJJDBBFCDCJCL@LHBBPARBHLHBNAHAJINEHBJCF@FDAPADWPABBHBBJBLJPV@RPHRTDBFADINCHBJELBF@FKFCHBLFBF@RBLB@D@HIFAN@DBBDAFBFFFDHCPGDAFAFBJCFLXLJBDAXBFPF@B@DR@NFDDBDCFSPCHOLCHFFJFTFBBNCF@LHFDJBBF@FGF@BJHFRAFEF@DDDAFAD@DDBNDLJ@RGPBLHXPNFTDBF@DBBFLJJBBDJJDBHCF@VVBAAEBALCTMJFF@JCJBHCDBHCHGDAVCZDFHTEBJFBVEF@DBPBTHZCDF@D"
                ],
                "encodeOffsets": [
                    [
                        122853,
                        30388
                    ]
                ]
            },
            "properties": {
                "cp": [
                    119.839506,
                    28.929524
                ],
                "name": "金华",
                "childNum": 1
            }
        },
        {
            "id": "330800",
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    "@@JFLDLFNHBBF@RVBD@FBBHBFDB@DEB@AFBDFFBFGLC@A@BEAGAA@FC@@CCE@HA@EAC@@BPHBBCB@ACCCDDLAFEB@FATADID@LOfYLCFAJCDE@ECABBFNJ@FBDPFFCBBADH@D@@DCBEACBFJHBFL@FFPHNEPD@BCHC@FGH@BDBD@ADFB@BFFF@F@BD@DI@BHGHC@@DBB@BGEEBE@@BCB@CA@C@BCECCAEDENC@CBEJGDCBAAE@AAEBAAGDCCMLFHFDD@DC@ADA@B@BJA@DHDB@@AFA@DADHB@DHHCFGDCHAAGICACBDD@DGD@FCA@BDBABCD@DDCCFD@CJB@DIBB@DEFCFAACJBBLBBBMDAB@DMFADDFCDBBEFAFBBBHLABFCDBHCDHDFABB@BD@@BABAA@@CB@FAFBDABA@CCC@CBBDAB@DFHCBAFBBHDBCCA@AFBD@ADDADD@BABDB@D@BBABB@A@BABB@FABNB@BDABEBCF@BCBEN@FA@DDCBDDF@HDDDIBFFAJDFAFBBCD@F@D@BFBADGFMCCFE@@BBB@DEB@DBDHA@DMHADEBCAEHCBKACCEBBDCFDBBHLDFDAF@F@BABCCEFDDHCBBCB@FCBCDEA@BABB@BDJ@DBCDA@GDC@@FBDKFB@JB@FB@ADFB@BC@AB@BCAC@ADDBA@CA@ECBBDAJCBBDBFCB@HBBA@CACB@FDBAJCDBBB@FDADEDCFGDCLFDGF@DEFEAADG@CDG@@A]BKAOJGBCDK@ODCHGC@FILRLCFBBABC@EF@HGREFE@@NCLEJ@LAHEHEBATGP@HEDM@GHA@C@GGMBKCIEGAECIAGEQGE@ICIBCJBJFFRFTXLHDHHH@BCBADIDIAEBCJABC@ECKD@JELKLELGBEFIAEFCBABGB@BECEBCCC@BDA@ABOC@EBGCA@DABIBGD@BE@OXBDHDAB@HFHEH@DCDMIC@CAEABCGGDECCAMSAHLFD@JH@CF@DAHGCBCEEAECACEGJEN@\\CLGDIJOD@FBDKJAHBDTRCJBJ@DKJQDMJQDKLCF@JJPTFBB@FIHIDIJJV@NDHCHBJEFKFGBCBCFBBJPFdBDD@BB@JDPJJHDHCFA^DN^DD@DCHDHIFADDX@DFJED@VAHIH@DFDH@dIRAFDJLFBFAFI`GPHPAbVN@DB@DCLIJIF@BJBRLFH@NDBHDJJLBLFDFDPALINJR@B]VCH@DBBLCHBJPPV@JFFRHL@F@HFNHF@LIZDFAJGVFFCDGFAJ@FDNANDAhBV@DCFCRCFCNCFBLAHBHBDFBN@NBH@BCFKHIPIBEBUHMBIFATCFAP[HCLADKHEJARDJCJEAGCEII@A@ADCPAFCNEBEGKBENITKFAFBFAJOTMNARNPBHCDERAHERHFBHAFABCAIIQ@CHBL@VCDCBGNADAVFT@FCJGJBD@BABIPFJEFGAMVSHGEMHGLONMJUBGAAA@IFMNCLCAMFC@AE@GEI@AFIDIHMAGOOLMBEFEFMJ@HBD@BABA@GBQAGGEACAADGT@\\JfHL@RDHCZQNENBPRPDDJBDLHHDT@\\RANBJINDPDFD@N@FBDFBBBDFBDPNBfZJBJCJBDH@FNFFFHHNBJFDDBLHLRPRHPGF@DBDJPHFCDENIHINEHI`EBAHIDCZEBA@ECCSGEEBCFEDAPSB@HBFGLKBADBHSJKEGBI@IBGJGFGHCFODATJdFNDPJT@PHL@NCD@HFBDFDN@DEXAdTF@LAEQBIBANAFFJ@LJDANKPCDCLKBGZCJV@DADGH@FBBFBDANBDKDAF@DBDDELBJ@RBBDBSLGJCBECCBCB@D@FLNFDF@BD@BGBBBAB@FCHBLLCFGVCLFHC@ACKBAHEDCDOHGCQB@LB^GD@MIIQIIUO@GDGCEBICSGABAPCHCDMCMFGEG@ELOLE@ECE@MFEVEBABAB_P@PEFCLOPGDCCSDEFCD@LDLAJDDCHQFCAGEEACDWJGACAK@EFMBSCCABADCFARCBAC@QKoBEFEBCCC@GHCBGEIGIIGU@CA@CBELGFODSFIHIHQ@IFCHSNEJI@QAKEGWFGABCPIDCEQCCGBGJE@ECIOEaBABBLFJ@HABBDJDDB@D@LIBCAAKADE@ACCAGRUBCACEEUGECEM@ECDCLCDGBA@EEMICAMFO@GAICAE@GISWQGCIKAIGCOAcHMFMAeDCAQWEIIGO@YMKCKCWAE@_LMBGAMME@KHMISAIIMEIGCMCEGEGAKBEAKKYOCGEECICCE@IIMWICKOIGMQA@IJEBGEQ@UIIM@QCIKKAEBUKGEMBMAOHGBCBIEGGEIOKKMG@IACMGGMCAEAKDCDALCDIAEBEHAHABG@IAE@QLGDG@OIIKEEE@GBG@UIGEAGEIA@EBCDCAGHCAE@KDGAAGGI@CAACEOGCICAI@EKBKFAFMGQAQ@CJCBCEYGU@CHEGEAC@S@CFAD@FBFJNCHBNDFA@AAC@CFCBCAOEGGEEOEGGMAIFICKSYEEEICAGBIIIAKGAC@OEEBKKOGUOYMOKAI@IDIJE@IEM@MYMAGGG@UBMEIFAB@LFJAFKLEJGDSAKDWESHAA@C@E@KAA_GWAGBQTC@EGGAACAKCG@@HCDGD@@EAABAHB@ACE@EMCGMIFMLGEKDKECDE@ABGBGDCFGA@F@BJJADS@ABFF@FCBGACREFHR"
                ],
                "encodeOffsets": [
                    [
                        121277,
                        28968
                    ]
                ]
            },
            "properties": {
                "cp": [
                    118.87263,
                    28.941708
                ],
                "name": "衢州",
                "childNum": 1
            }
        },
        {
            "id": "331000",
            "type": "Feature",
            "geometry": {
                "type": "MultiPolygon",
                "coordinates": [
                    [
                        "@@CB@BFDD@@EEA"
                    ],
                    [
                        "@@WBA@CD@FBBPL@B@DCDADBDDD@BABCAOCCD@JDBP@DBJHAFBDTFB@BCEIDCDIBAD@LBHAJ@BCIKEMI@@EFEAEA@I@C@GEMC"
                    ],
                    [
                        "@@CBDLDDH@DBDFBJBDLFDHRCBB@DDBT@JBF@DAAGCEMKOCEAMMAAEBCHA@ECCEKAGGC@"
                    ],
                    [
                        "@@@RH@BAAKBOEAADAJ"
                    ],
                    [
                        "@@FBCICBBF"
                    ],
                    [
                        "@@B@@ACEGCABBDJF"
                    ],
                    [
                        "@@EHABFH^DFFDHJHDBD@BCCOCEIAEEEAGGIBIC"
                    ],
                    [
                        "@@CB@BBLFLHHFFPDFLHDDBBAHMKQCAGFG@GICMKEEC"
                    ],
                    [
                        "@@BBH@D@@AAEEAEB@F"
                    ],
                    [
                        "@@@AAAC@AB@BDDD@@C"
                    ],
                    [
                        "@@N@BABAOC@DCBBB"
                    ],
                    [
                        "@@BFBD@BCA@@@DFFB@BACI@CACCA@B"
                    ],
                    [
                        "@@D@CE@CGABJFB"
                    ],
                    [
                        "@@FDD@DCECAGEAADBJ"
                    ],
                    [
                        "@@DA@CC@CB@BDB"
                    ],
                    [
                        "@@A@BDB@B@BCE@"
                    ],
                    [
                        "@@B@@AC@ABD@"
                    ],
                    [
                        "@@@AC@DB"
                    ],
                    [
                        "@@@@B@@@A@"
                    ],
                    [
                        "@@DBDAACCAAB@D"
                    ],
                    [
                        "@@JABABCAEEAEBOIE@C@@DDDDDH@FF@FD@"
                    ],
                    [
                        "@@JBDA@AIAGEC@AB@DJD"
                    ],
                    [
                        "@@FB@DD@@CDBHDDAAAGCMAAB"
                    ],
                    [
                        "@@BB@AA@"
                    ],
                    [
                        "@@B@A@"
                    ],
                    [
                        "@@@BDDDAAA@KADEA@BBD@B"
                    ],
                    [
                        "@@BAAAGDABB@HA"
                    ],
                    [
                        "@@AFBBJBDC@EDA@CC@CBID"
                    ],
                    [
                        "@@BB@DMH@DBB@FDBF@FBD@ACBCDADBBKFA@AEA@GCCE@EFC@@B"
                    ],
                    [
                        "@@BDFFDAB@AGJCBCDBDCCIA@C@BFA@ADE@EDGA@BDDCB"
                    ],
                    [
                        "@@DCLB@AAEBCCACAIBIF@DABGACDCFDBHEDB@DJADC"
                    ],
                    [
                        "@@ABBBP@CEKB"
                    ],
                    [
                        "@@CHFDFBBCA@AIE@"
                    ],
                    [
                        "@@FBBAAAECCBDD"
                    ],
                    [
                        "@@@DFBFAFBDACEGACBABC@"
                    ],
                    [
                        "@@@@BDF@ACE@"
                    ],
                    [
                        "@@A@HDB@AAF@AACAAB@@C@"
                    ],
                    [
                        "@@BBB@CA"
                    ],
                    [
                        "@@ADD@BA@CF@BAGACF"
                    ],
                    [
                        "@@@BFDD@HFDA@ACABAAAQA"
                    ],
                    [
                        "@@DHD@JFJAAAKAAEC@AACAAB"
                    ],
                    [
                        "@@@KIG@DEB@@HFAHBFHBBFD@@CJ@@CKACC"
                    ],
                    [
                        "@@A@DDCB@@FDFABBD@@FF@AFFF@DE@ED@FFDL@FFEFHD@DIDCB@BHFJBBBDDFAD@@EH@DCGIBAJ@DA@AECOBA@@EAC@CDA@AIE@ADC@EMGEASKK@"
                    ],
                    [
                        "@@@DN@@D@BI@ADBB@BGAABDDFBBHDC@FJBB@@EDA\\DPJF@@FF@HJBBHCZ@BCAAE@I@ECGBCC@APAECEAIDQECAGIAACAG@GGBCF@DC@EDA@A@CE@ACGA@CE@ID@DDDABK@EAE@@BDBBDDBABC@"
                    ],
                    [
                        "@@HDFAGCC@AB"
                    ],
                    [
                        "@@BDFABGC@@BCB@BA@"
                    ],
                    [
                        "@@ADBDAFBBD@FAEEFGHAD@BAEAAAEBIF"
                    ],
                    [
                        "@@AB@BDDDBBFDB@CH@@GI@IE"
                    ],
                    [
                        "@@BDHBIE"
                    ],
                    [
                        "@@ADDHDBFBFECABCGEGB"
                    ],
                    [
                        "@@BHFBBE@ACACAAB"
                    ],
                    [
                        "@@JD@HHDABFABHDB@DD@@CFDBA@AIAAIB@@AKCCEICE@BD@A"
                    ],
                    [
                        "@@@DD@DA@CAAED"
                    ],
                    [
                        "@@@DF@DC@CB@@AF@@CEEE@GC@DDBDHAFC@"
                    ],
                    [
                        "@@CB@@HDJBDABE@ABAEEIFBDG@"
                    ],
                    [
                        "@@FDABDFBABAD@@GGGGAABBDADB@"
                    ],
                    [
                        "@@@BDBD@ACE@"
                    ],
                    [
                        "@@AFDDFBD@EGFA@CCCEAC@@BBF"
                    ],
                    [
                        "@@ADFB@BABCB@BHBBDLB@ACE@A@AFABCCEDAAECAABAFK@@BAB"
                    ],
                    [
                        "@@ABHDFA@ACCGB"
                    ],
                    [
                        "@@CBFDL@CGC@AAA@CBBB"
                    ],
                    [
                        "@@ADDBJ@AGCCEF"
                    ],
                    [
                        "@@B@AAA@BB"
                    ],
                    [
                        "@@B@ACABBB"
                    ],
                    [
                        "@@BBHAAAABAACB"
                    ],
                    [
                        "@@ABABFDRHFA@AKI@AHA@AAAICEBG@@DFDA@"
                    ],
                    [
                        "@@BB@DHBBA@AB@EGCBCAABBB"
                    ],
                    [
                        "@@HDDAEEG@BD"
                    ],
                    [
                        "@@E@@BDDHBDCAGE@AD"
                    ],
                    [
                        "@@F@@ADABAC@ABC@AD"
                    ],
                    [
                        "@@BFJ@@AC@CCC@"
                    ],
                    [
                        "@@BDFB@CECAB"
                    ],
                    [
                        "@@DBBAACC@@D"
                    ],
                    [
                        "@@@D@@FBBCCAC@"
                    ],
                    [
                        "@@@BFBH@AC@CA@G@AB@B"
                    ],
                    [
                        "@@DB@BF@ACG@"
                    ],
                    [
                        "@@AB@BDBBAB@HDBDCBHBBABB@BFDDAEGBC@AEBACIAECEB"
                    ],
                    [
                        "@@KCABAH@FDDCBHDBBG@ABAAABHLFFFB@CACDICEH@DCAA@AAA@CEG"
                    ],
                    [
                        "@@ECCDEA@BBDD@FDD@FDD@@EBA@EE@@DEA"
                    ],
                    [
                        "@@HBFC@ACAAABACEAB@DA@@BEDDD"
                    ],
                    [
                        "@@FB@@@AAA@ACB@B"
                    ],
                    [
                        "@@ABD@@AA@"
                    ],
                    [
                        "@@DDF@AIGB@D"
                    ],
                    [
                        "@@@BBB@AAA"
                    ],
                    [
                        "@@B@A@"
                    ],
                    [
                        "@@BLDB@ECEAA"
                    ],
                    [
                        "@@BBD@ACC@@B"
                    ],
                    [
                        "@@BDHJPDP@BAIEKCAAGAECEB"
                    ],
                    [
                        "@@DABCAAGB@DDB"
                    ],
                    [
                        "@@DBADCBA@DB@BEAED@BFBBBF@BB@BB@@ABAH@B@JFJ@BBHA@ACABCG@AAEA@GCAGBACEAACCAA@AD@B"
                    ],
                    [
                        "@@B@B@CE@F"
                    ],
                    [
                        "@@`RZbNB\\DZ@`BXHNJHfHr~NVFNHC@FCAAHNlCNKJGLHBBHFEHBND@DCBAB@BLJDDXAND@JJRAHBBLDBBKJGBYROBIAA@AD@DFNFBAFCDSAEH@FCDALEFHFABEDE@OJ@B@LEBEBG@AFE@CNGRC@CFBF@LEBILKHEJEBC@CCE@ADBDCBEACASAOVOHG@GDCCGOMIIM@M@EEKEGGCCEAGBIAAIEQ@WCKBKFE@CCACEBAACCAEK@CJCDICGBG@AA@ICAIB@FGBCFEDIAG@GDG@I@GPGFBFDFBJBD@HCBMEBCDGEGIDIF[DE@YSCECGKCOAI@IFG@[DEHEDEF@F@H@FMLIAG@EHGAGJCFBFJLFLDFCHOJGHALCJmLC@EFADDFBLEFKIIBILKAKHC@I@GCC@CLDNCBGBEHMDICIIIAM@WPC@CAGIA[GIKAGGWAKCODEFIBMIGAEA@CPO@EDGMCECGFE@EFGECEEA@AFKFEAEBM@AEEGAKB_@UACCC@CBEHIDE@EEAEQBEFOCMTKFMDINIBMFGCMFCDAFDDGJELOLE@CCA@C@KLC@GAOAMCIBGEAOK@IKAMHK@AGO@CDE@CCKA@IBCABGEE@CDEAECAIKBAA]JICCKGKKEDCACE@CHC@CGMEBCJEBCB@J@BA@CNEF@JGHEBIEC@CFEBoGKN@FDDADC@SFEFAFEHCBEAEKGOAAG@CDKDABBF@FELDFCHAHBH^VDFJLFAHED@D@@JHJAHCBCAABADFFRND@RILCZNLCLGD@DBHLDLAHCDADFF@FGHGBEBCHBH@DADGDCFQDIPFHF@DBBRM@EHE@QHSTEDAFBbFPLPNDHFLCLJ@FCFAFBJCBIAEABLHDNDDDLBFFHF@BADDN@BCB@LBDAHLRLJLTF@HCL@D@FF@HJFBDADCFBHNNBTLNRFHJPHPBTCFAJDD@JCFIAIHCBBHHADADDDFDCH@BBBNDHABFEDBDHBDDORBHDDNBLDBNAFFHDFJGCEJIFANBB@FCCCC@AC@GDEBAJAFDD@RIR@LDHHRDLLBDDFJFJDJLDANDLHL@nJJJJFFJHFBNAFGJ@LBFHNJDFPBFAVBFHHTBLFHA@EDGLBTAFBDF@DPDDDAJEJC@AD@BH@HDCL@LCHA@EECBBLFJ@DIBCDANEDEAAACUCCGDMPCTBBHADDBDQLABVR@HFJBJADCHMJAF@DBDLLRDHJJJJVB@LILALBFFBLOBGNCBKDIGCBCLKPFJJBHNNNRH\\VDDDJFFTJPLIL@BHF@JLJBBMJXFdLH@RETBRJNRRNDBNALODCD@DDD@PKD@LBLADBBBEZKNALBHDBPFFDAVBRHHPHFALKDEBCbCHILEFBFVJP@JFBJ@HBXBNBHDPPL@RCBE@IDCFA`FLHHLHFdAZEV@DA@CEK@G\\EH@HBDJBTEL@H@FHJLDJ@LCPIHAJDLPFIAK@IDAFAL@D@DHFFBANILCMEFKBALHFABE@GCG_UEEDEIKCM@GFKBMG@MBC@CQKKHQNMBGJEEGIEEGHEJC|EZDPADADGBCLAAQBEJSPMHG@GDEBAFBDA@C@AFBDDDAAAMK@OBWAMEGDIP@NG@AECFILCFGLABGJ@HBAJFF@HDFGLBBNBNCBA@KBAH@DHLPLHPDLJDHHHCDBFEF@DFL\\n@FKL@HLFNDVRFADATSHILGAGDOEEAEDCDCDAPBFBLATDb@LAJETONGPApEbGN@HHZdPXFDJDR@GLqDC|_\\QDE@G@KK[GaDUDEFGePIJKFS@MGuDSJKdUPIz³HSBQC_GGICMCiBNRG@IEnGJCJQV{DS@WCQGOG]K­GUKSWMkQ·UabUXedPSDAfGhQDGFSFyHSNQ^aFKBOMwVCNEJOJ[BUCIGCyQCCBCDGAKKOMKSICGAI@CFCPBRHPHD@BADSBALHDABCAAGC@MACY]M]GOCGBGHM@ECEMEEECQGKGEEC}IICGEGACDCRKPALANDRCHKHsXYH[FY@ICKEGIGMEIeYCGAGBSCGQWwiKKU]E]MWCYEGUIAACYCIGCOEKAQBEBCDOViTIDW@ICEC@EDQBIJONQFODMAWOiIMWMYYQMmK¿McBQDIDGJERCT@ZAP[°INQN"
                    ],
                    [
                        "@@BBFBCCC@"
                    ],
                    [
                        "@@EDBBH@F@ECCA"
                    ],
                    [
                        "@@B@ACCBDB"
                    ],
                    [
                        "@@FCHDFED@FL@BA@@FHB@BAFEBBBBBVCFCDEAAG@EE@AJ@DEDBB@FADBDAHHNJBFF@BDFABCACOICKBCAACC@CCA@CG@CAC@ADGABHEBAHSFIIC@AAE@ICA@KL@DHFD@@BL@BAAAIAE@AA"
                    ]
                ],
                "encodeOffsets": [
                    [
                        [
                            124850,
                            29221
                        ]
                    ],
                    [
                        [
                            124815,
                            29155
                        ]
                    ],
                    [
                        [
                            124795,
                            29107
                        ]
                    ],
                    [
                        [
                            124867,
                            29125
                        ]
                    ],
                    [
                        [
                            124840,
                            29096
                        ]
                    ],
                    [
                        [
                            124246,
                            28812
                        ]
                    ],
                    [
                        [
                            124259,
                            28762
                        ]
                    ],
                    [
                        [
                            124419,
                            28746
                        ]
                    ],
                    [
                        [
                            124698,
                            29479
                        ]
                    ],
                    [
                        [
                            124716,
                            29490
                        ]
                    ],
                    [
                        [
                            124567,
                            29231
                        ]
                    ],
                    [
                        [
                            124569,
                            29210
                        ]
                    ],
                    [
                        [
                            124821,
                            29091
                        ]
                    ],
                    [
                        [
                            124838,
                            29076
                        ]
                    ],
                    [
                        [
                            124787,
                            29411
                        ]
                    ],
                    [
                        [
                            124785,
                            29380
                        ]
                    ],
                    [
                        [
                            124715,
                            29328
                        ]
                    ],
                    [
                        [
                            124717,
                            29331
                        ]
                    ],
                    [
                        [
                            124720,
                            29337
                        ]
                    ],
                    [
                        [
                            124757,
                            29347
                        ]
                    ],
                    [
                        [
                            124741,
                            29298
                        ]
                    ],
                    [
                        [
                            124738,
                            29288
                        ]
                    ],
                    [
                        [
                            124786,
                            29298
                        ]
                    ],
                    [
                        [
                            124674,
                            29303
                        ]
                    ],
                    [
                        [
                            124722,
                            29296
                        ]
                    ],
                    [
                        [
                            124669,
                            29792
                        ]
                    ],
                    [
                        [
                            124608,
                            29824
                        ]
                    ],
                    [
                        [
                            124607,
                            29815
                        ]
                    ],
                    [
                        [
                            124608,
                            29795
                        ]
                    ],
                    [
                        [
                            124616,
                            29787
                        ]
                    ],
                    [
                        [
                            124593,
                            29760
                        ]
                    ],
                    [
                        [
                            124603,
                            29758
                        ]
                    ],
                    [
                        [
                            124592,
                            29764
                        ]
                    ],
                    [
                        [
                            124700,
                            29674
                        ]
                    ],
                    [
                        [
                            124690,
                            29677
                        ]
                    ],
                    [
                        [
                            124687,
                            29685
                        ]
                    ],
                    [
                        [
                            124719,
                            29657
                        ]
                    ],
                    [
                        [
                            124720,
                            29654
                        ]
                    ],
                    [
                        [
                            124727,
                            29654
                        ]
                    ],
                    [
                        [
                            124770,
                            29531
                        ]
                    ],
                    [
                        [
                            124727,
                            29442
                        ]
                    ],
                    [
                        [
                            124749,
                            29455
                        ]
                    ],
                    [
                        [
                            124762,
                            29462
                        ]
                    ],
                    [
                        [
                            124774,
                            29424
                        ]
                    ],
                    [
                        [
                            124787,
                            29390
                        ]
                    ],
                    [
                        [
                            124820,
                            29358
                        ]
                    ],
                    [
                        [
                            124843,
                            29139
                        ]
                    ],
                    [
                        [
                            124776,
                            29106
                        ]
                    ],
                    [
                        [
                            124828,
                            29078
                        ]
                    ],
                    [
                        [
                            124646,
                            29057
                        ]
                    ],
                    [
                        [
                            124639,
                            29082
                        ]
                    ],
                    [
                        [
                            124563,
                            29031
                        ]
                    ],
                    [
                        [
                            124605,
                            29069
                        ]
                    ],
                    [
                        [
                            124608,
                            29066
                        ]
                    ],
                    [
                        [
                            124600,
                            29052
                        ]
                    ],
                    [
                        [
                            124567,
                            28976
                        ]
                    ],
                    [
                        [
                            124583,
                            28979
                        ]
                    ],
                    [
                        [
                            124579,
                            28970
                        ]
                    ],
                    [
                        [
                            124599,
                            28958
                        ]
                    ],
                    [
                        [
                            124606,
                            28949
                        ]
                    ],
                    [
                        [
                            124615,
                            28944
                        ]
                    ],
                    [
                        [
                            124656,
                            28946
                        ]
                    ],
                    [
                        [
                            124626,
                            28921
                        ]
                    ],
                    [
                        [
                            124629,
                            28928
                        ]
                    ],
                    [
                        [
                            124562,
                            28929
                        ]
                    ],
                    [
                        [
                            124554,
                            28903
                        ]
                    ],
                    [
                        [
                            124568,
                            28896
                        ]
                    ],
                    [
                        [
                            124584,
                            28889
                        ]
                    ],
                    [
                        [
                            124487,
                            28924
                        ]
                    ],
                    [
                        [
                            124478,
                            28927
                        ]
                    ],
                    [
                        [
                            124470,
                            28955
                        ]
                    ],
                    [
                        [
                            124512,
                            28921
                        ]
                    ],
                    [
                        [
                            124531,
                            28926
                        ]
                    ],
                    [
                        [
                            124333,
                            28888
                        ]
                    ],
                    [
                        [
                            124332,
                            28884
                        ]
                    ],
                    [
                        [
                            124311,
                            28806
                        ]
                    ],
                    [
                        [
                            124301,
                            28795
                        ]
                    ],
                    [
                        [
                            124325,
                            28754
                        ]
                    ],
                    [
                        [
                            124327,
                            28725
                        ]
                    ],
                    [
                        [
                            124328,
                            28713
                        ]
                    ],
                    [
                        [
                            124402,
                            28804
                        ]
                    ],
                    [
                        [
                            124407,
                            28807
                        ]
                    ],
                    [
                        [
                            124403,
                            28772
                        ]
                    ],
                    [
                        [
                            124440,
                            28777
                        ]
                    ],
                    [
                        [
                            124448,
                            28781
                        ]
                    ],
                    [
                        [
                            124447,
                            28741
                        ]
                    ],
                    [
                        [
                            124449,
                            28742
                        ]
                    ],
                    [
                        [
                            124053,
                            28686
                        ]
                    ],
                    [
                        [
                            124848,
                            29394
                        ]
                    ],
                    [
                        [
                            124846,
                            29397
                        ]
                    ],
                    [
                        [
                            124325,
                            28786
                        ]
                    ],
                    [
                        [
                            124015,
                            28815
                        ]
                    ],
                    [
                        [
                            124678,
                            29407
                        ]
                    ],
                    [
                        [
                            124654,
                            29401
                        ]
                    ],
                    [
                        [
                            124683,
                            29383
                        ]
                    ],
                    [
                        [
                            124672,
                            29380
                        ]
                    ]
                ]
            },
            "properties": {
                "cp": [
                    121.288599,
                    28.551378
                ],
                "name": "台州",
                "childNum": 96
            }
        },
        {
            "id": "331100",
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    "@@EC@KACBEAI@EKAMMBGDEFCHKAMBGEKCI@ECAQR@BBHSJQBGDECEE@OACBCBA@AACKAAEBCDKFGDAFBDABEIKKC@EBKAE@APGR@LCBADI@I@A@CBMKMQEBEVGNFPABCAGJMVCL@JOFCZEDQBKBEFEJ]@KIQFIJAHADAHSAAGCAAIIGKEIKCCGAK@KD@DBREBEFCDIAEQCIECGAEBADEDCBGDCEIOBMCcOAA@GJETEBCJCDABCEIBCJEBGSSIOCBKIE@GBMCOGEGBEGC@GDALEBGDEBECMCEEAAAEBMCEDG@CAAC@ECCAGHEBE@YIEEYIMAEAG@CDARAHADGOECGEGIIIC@DCRABGBUCGBIAM@ecKCK@GBEFDH@BGBOEEWBIAGGI@C@CECQCEDQFGAMBK@GBEFCD@FCB@BAACFKDIF@LCBBL@LAFEHGDMACEEBA@C@IDC@A@CEEAIBGDE@CDSDWAKA@DA@CCAIAAEAOMK@CJA@A@MGEGAEHG@CCGCAi@IAECGMMCIBEBONC@AABGKCEGFABBLAFHNCDHF@HCD@DEJCDAAACGBMCEBcIIIOGIGGCGBIAEEC@CBS^CDEJA@SO@CBGAC@OCCCBCJINGAIBYICIhg@AOGKMEQQ@MJGHEDG@KAIGGAMMFCAKFEHGF@DIEQM]IEACBEFEBCGK@C@YFEJA@EOGCE@OHG@AEC@CDACI@CECQBAB@F@JCFCAIKIACECDAD@@CIFC@CIKACQOEGCGQBCAIMGESECBE@gSCGAOACGCGGEAAEAAOGK@EMFG@SDCFA@ACGGAECGYIGEAQBIBADEDEAIBG@OEA@CIKCKBCBEFCBA@CEKEAAGDGEC@CBGAAB@B@BAJGBCHG@AEFK@ECGEAUDACAIACECEBEDEBEGM@@IC[BEEEDGAGFM@AACWQM[F]CMKS@QCKQY][KCOEIJGLCN@JILKFk@eIKEUOSSIGEGDA@I@EFABEAAEA@ABEC@EGKGMCKG}YMGMc@CAECCAAEIEKKAEBGBGCEC@F@JAFABEC@QICAAEFYCOHIBECCCIBIAEHMFIFC@IEI@A@EFECEAIFCAGCCB@HEFKBC@GCE@MJ@BBHBJDL@DCDGFADJDP@BDETEHGDODKIMEIGECCEGCC@GBGLEBE@KICAQLALUHCEC@EDOTKFEHGBWCM@GFGHOI@EDCFCFE@CCEBEAGGCMBOEG@MIDABCBEIUECILUFCHEBC@MAI@CAQAKDEDBJITGFIAAF@DDD@LCHCHKCCDDD@DEBAB@DBBALEDAAMCEAIFAFBJDFHBLVZFNJJRDNHFRDDFGDEF@L@NAFHHAHDJBNHFBJADCBI@EDBNABCDFLAJILGNOJKLAF@FGJAD@FHFDFBFAFILBHDBN@VAH@BF@DGJBJE@IAILINEDIDWrILAPABI@CFMFDFELFDJDF@DBAFEL@PAFKHEHERDFADAHQPDDDDBNBFFF@HCJMFALLLEBEDIL@P@DILFH@DcD@BBDFDAHgRYFABKDM@G@ALafIDCF@LDPAHDDGLEH@TFTJPBFCJCDKLIDAH@^@BJ@HLNHDHFHDBDJBBNHLCLFDRFFLDN@JAD@DBHLTJCDBJCPFNFZANCJIHUHI@OGQCG@AB@F@FV`HFLBFDTVTDDJBHHLDJADGFGNCDKD_@GF[HQH[\\@PAFYF@LBHDJ@LCFKLEDKBC@GEGBGAALFF@PBDLHJBJJHADBFJFFTZDLEJ@DJTFHFPLJDTADED@DDFCBYEMDCGCAIACB@D@TBDHFGF@DHVFZADID@DBRHRENEBALFLJ@DBDJPHDFBB@DLTJ@HCF@DBHGDBDCFAB@FJBHHFVJH@HAF@FFJLTJF@XOF@JBH@BABGFGFAJBDCBKDCLCFBDBHNNHBD@JNHLLJPHFFHAJADGHBPANFNLHAVBFLLDJ@RJNVJR@HFFAJIB@NRJHLPJDNXJJF@DDDJFFDHZPLLFBLAHBHFDFDNJHNFJJTBNJLGF@NNHBNA`KF@XBLDLDZNP@JHFJRXDBfCNBNEdGPBHDBJJLHDXRJT@HBFJDHBP@NEDBNJFFLABCFOJ@DABCE]BGNMHWJGPADBJHDF@HBDNHDBDTLDT@NGDG@EHAJOHCFCDUFCJAB@DDRJXBHFNBPJFBDAFABCBEAIBKNSQ@OFCC@SDS@OBQAGAQEKAIFSBQGSEC@CL[FCH@PJN@FC@MFEbSHEBUCICGECIOEK@ADGCM@SCABA@ABGHCFDFDFPFDF@PEVCDADE@IAE@CJSFAF@n@HGBG@AV@JHD@JCXBLB`CL@FFLXBBDB\\E\\SP@\\BPFDDDH@LTRBF@JDHNLLNHFDD@LBDHBV@HALEDABBBFBHJL@LADCBkZFZJFPBJENINCF@RHPTJJHL@HCF@FFPB\\BFBDXNRRLFDLDBHB^BBBLVDFBHADCHLLJDDADGH@PLFHBBAFDJHJPJBDAHLFB^PBNGPAFCDEH@LDJEJDFLDBJ@HDBGDCPCHGNEDCJBBGAE@ELCJGJCFKRFXDh^HDJJLDJBDCBACAAKRQPAH@BA@GBANBFELAJ@JJJVGJBDBBNBPGRCDABET@FBDJDD@BBFL@RCJDJJDHADOLADDLJLLNFFBNXJRPDNLPFDZHBBBDAXBdEL@DDDBFABK@EBCBJPHJGJ@BHJF@FD@DAFDBFHFBFMBIDCAGBCF@PFRAJBDAHD@CCIBCFAHIBEAEGGCE@UCCC@ACRIJABKAG@@JGTGHG@CFERCBMDAF@@EFADG@ERARILBJIF@HJBL@DCDBFFDFJFDFC@IDGPDDHDBHIDUDIECC@KMASMMAEFKACIE@GAAGCK@GDE@KSKIKQBGAC@KDA@ACMBC@AGEEEKACCMCGCAKFBJBDAAIBEDE@EKIKDGEMCKOEOAaBEFCTSRGF@FGN@AQCAE@EGJORCDEHCBC@CAGDGFAHAHG@EEEBCDCBGCKGKCAC@KHKDYMKDQJC@QMEEBCBADBDABGGI@IC@C@GFEBIKCE]UAGBGDGCEFK@EAEBALCDCH@BBHPFLDBDAHGBEFETED@BCCC@ELMtHBADED@JFHADEBA@IFEDM"
                ],
                "encodeOffsets": [
                    [
                        123278,
                        29163
                    ]
                ]
            },
            "properties": {
                "cp": [
                    119.401786,
                    27.951993
                ],
                "name": "丽水",
                "childNum": 1
            }
        }
    ],
    "UTF8Encoding": true
}